name: MSBuild

on: push

env:
  App_Name: GithubActionTest
  Solution_Directory: 
  Solution_Path: GithubActionTest.sln
  App_Project_Path: GithubActionTest/GithubActionTest.csproj
  Test_Directory: UnitTest

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
